### ISSUE TITLE
Needs dependency bumps to build on aarch64 and riscv64 freebsd

### ISSUE THREAD

**Issue by clausecker** [rwestlund/paladin#18]
Dependency `golang.org/x/sys` must be bumped to `v0.5.0` to make the port build on AArch64 and RISC-V64 FreeBSD.

**Comment by clausecker** [comment]
I have prepared a patch to do this on the FreeBSD port which I'm going to commit in the next few days if you have no objections.

**Comment by rwestlund** [comment]
Thanks for the heads up, I've updated from govendor to go.mod, bumped dependencies, and tagged `2.0.2`.

**Comment by clausecker** [comment]
@rwestlund Once you file a bugzilla PR for the port update, please let me know so I can commit it ASAP.  Also check your other Go projects if any.
